pipeline {
  agent any
  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/your-username/smart-expense-advisor.git'
      }
    }
    stage('Install Dependencies') {
      steps {
        sh 'pip install -r backend/requirements.txt'
      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t expense-backend ./backend'
      }
    }
  }
}

