pipeline {
  agent any
  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/Nivesh1020712/Smart-advise.git'
      }
    }
    stage('Install Dependencies') {
      steps {
        sh 'pip install -r backend/requirements.txt'
      }
    }
  }
}

